#!/bin/sh

set -e

go mod tidy
go build -ldflags='-s -w' -o "./dist/fzfg" -- "./cmd/fzfg/main.go"
[ -d "$HOME/.local/bin" ] && mv -v -- "./dist/fzfg" "$HOME/.local/bin/fzfg"

mkdir -pv -- "$HOME/.config/fzfg"
cp -av -- "./configs"/* "$HOME/.config/fzfg"
